spring.application.name=sistema-academia
spring.datasource.url=jdbc:postgresql://localhost:5432/academia
spring.datasource.username=postgres
spring.datasource.password=admin12




spring.jpa.hibernate-ddl-auto=validate
spring.jpa.show-sql=true


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.repair-on-migrate=true
spring.flyway.clean-on-validation-error=true
